### PR TITLE
Adds a user account module.

### PR DESCRIPTION
**Pull request by Jjk422**
Adds a user account module, currently not modifiable by facter or scenarios files but will be added when parametrization is merged.

Currently creates a user account named user with the password as password.
Home directory in /home/user.
Shell as /bin/bash.

### CODE REVIEW

**Comment by thomashaw** [comment]
testing this now, cheers.

**Comment by thomashaw** [comment]
Hey,

Module works great but there appear to be some extra changes to unnecessary files included in the changelist. 

Please revert the following:
  documentation/yard/rakefile.rb
  lib/schemas/service_metadata_schema.xsd
  modules/services/unix/database/mysql/*

Please update the following: 
  scenarios/simple_examples/user_test_scenario.xml:11: remove comment
  modules/utilities/unix/system/accounts/secgen_metadata.xml:20: remove comment

If I'm mistaken and the changes are required please let me know but I have a feeling this might be due to using the refactor -> rename function in RubyMine on a symbol within your module, RubyMine has picked up some other symbols in the mysql module + the yard rakefile with the same name and also changed those. 

Cheers,
Tom

**Comment by Jjk422** [comment]
I didn't notice them, good spot.
I'll do the changes now and then I'll update the branch.

**Comment by Jjk422** [comment]
Just uploaded a commit that should fix all the issues.
I think the problem was that some testing files were merged into my local changes and so were placed to be committed, although the rakefile error was most likely due to RubyMine's refactor.

**Pull request merged**
