### PR TITLE
ESXi support

### PR DESCRIPTION
**Pull request by redwiz666**
Figured it would be easier if I went ahead and did a pull request. All functionality has been implemented (actually required small changes) and all base boxes rebuilt to support esxi (new links within each base xml file)

### CODE REVIEW

**Comment by redwiz666** [comment]
I just realized a few of the scenarios were commited. These were just changes I was messing with and have nothing to do with the ESXI support. I couldn't find a way to remove them from the commit

**Comment by Th3Prim3** [comment]
Just remove the scenarios and commit to same branch, pull request will automatically update.

**Comment by redwiz666** [comment]
ok I removed the scenarios. Should be good now

**Comment by cliffe** [comment]
Thanks for this, @redwiz666 . At first glance it looks like a valuable contribution. Since we don't have access to ESXi, I'll mostly focus on checking that the other providers still work, and do a manual review of the other code. Could you please confirm how you have tested this.

Due to the large number of commits which hit the same files this will take a while to review. It's going to be hard to confirm how/if the scenarios haven't actually changed without pulling this down and doing my own diff against the ones in master. 

It would be easier to review if you created a new branch from our master, and do a pull request with a single commit with all your changes (or individual commits that are addressing separate things). You could do that by either squashing your commits, or simply create a branch based on this one, and do a soft reset back to the last commit from our repo, then recommit your changes, which would result in a single commit with all your changes. 

If all that sounds too hard, I'll review it as is, but if you don't mind making it easier I'd really appreciate it! Let me know. Thanks again for taking the time to contribute to the project, either way it's appreciated.

**Comment by profzeller** [comment]
@redwiz666 If you do as @cliffe purposed,  I would be happy to pull and test to verify as this will be vital for me going forward. I may need to even extend it some. What virtual machine hardware version does it build? Would be nice to be around 11 for compatibility.

**Comment by redwiz666** [comment]
@cliffe @profzeller I'm not sure how to combine the commits into one (still new to using github). So I took the easy route and deleted the repo and re-forked. I added all the files for the esxi support into one commit so it should be easier for review. I will be doing a new pull request with the updated fork shortly. The VMs are build as version 7. I need to look into seeing if the plugin allows for specific versions is being build or if it only supports the version 7.

I have successfully build all the ctf and security_audits scenarios with no issues. I have scanned them using nmap to verify that puppet is running and configuring them. (different services running after each build) I have not had the time to actually try to get into them to verify on that end. I have also tested the same testing on the virtualbox VMs that it generates.

**Comment by profzeller** [comment]
@redwiz666 Sounds good. From when I was playing I remember being able to pass a variable in vagrant config. Away from computer but will try to find it.

**Comment by redwiz666** [comment]
@profzeller I found it. With using the plug in we can specify what version is built in the vagrant using esxi.guest_virtualhw_version = '9' and just pass it a version. Just need to add it an cmd line option that would allow the user to select the version to create. By default it does version 7

**Comment by cliffe** [comment]
#138

**Pull request closed without merging**
