### PR TITLE
CTF addons

### PR DESCRIPTION
**Pull request by Th3Prim3**
This is a series of new items as well as expanding existing for use with Capture the Flags.

**Encoders:**

- _base64_ - Expanded solution to give command from Kali when Internet is not available.
- _hex_ - Expanded solution to give command from Kali when Internet is not available.

**Services:**

- _parameterised_website_ - Expand service to allow change of mode on images from default 0660 so they can be downloaded. Useful if flag is embedded in image, so user can download image and use in utility to extract flag.

**Utilities:**

- ***NEW*** _leak_to_file_ - Utility allows you to leak a base64 file to specified location. Required by new generators and vulnerabilities to add file to target system.

**Generators:**

- _person_ - Expand generator to create add attributes age and profession.
- ***NEW*** _custom_list_generator_ - Generator returns a password from a specified list. This is a universal generator, user can add password lists to lib/resources/passwordlists/.
- ***NEW*** _pcap_ - Generator creates a pcap file with a flag/message embedded. File contains 100 packets of random TCP/UDP packets with random quotes in the payload. Plan to extend functionality in future.
- ***NEW*** _scenario_image_ - Generator allows you to specify a specific file from lib/resources/images/scenario that can be used in scenario. Useful in scenarios where you want a specific custom image so you can use in paramaterised_website versus the random_image generator.
- ***NEW*** _flag_8char_hex_ - Generator creates an 8 character hex flag. This is useful with CTFd when user has to manually type in flag and can not use copy/paste from the VM.

**Vulnerabilities:**

- ***NEW*** _jtr_crackable_user_account_ - Allows password to be cracked by John the Ripper with a default list on Kali Linux. This is useful for training students on specific utilities. It also releases the password that was cracked as an additional flag, rewarding them for cracking the password.
- ***NEW*** _ncrack_crackable_user_account_ - Allows password to be cracked by NCRACK with a default list on Kali Linux. This is useful for training students on specific utilities. It also releases the password that was cracked as an additional flag, rewarding them for cracking the password.
- ***NEW*** _pcap_file_ - Uses the pcap file generator to release the file to the system with flags and hints.
- ***NEW*** _zip_file_ - Uses the zip file generator but also allows expanding to add password encryption and release the file to the system with flags and hints.

**Example Scenarios:**

- ***NEW*** _examples/vulnerability_examples/crackable_user_accounts.xml_ - Example scenario to demonstrate the standard crackable account versus the new jtr and ncrack accounts.
- ***NEW*** _examples/vulnerability_examples/ctf_module_examples/pcap_file.xml_ - Example scenario to show pcap file generator/vulnerability.
- ***NEW*** _examples/vulnerability_examples/ctf_module_examples/zip_file.xml_ - Example scenario to show zip file generator/vulnerability.

### CODE REVIEW

**Comment by cliffe** [comment]
Great! There's quite a lot to review here. Looks good.

@Th3Prim3, custom_list_password is similar to random_word_generator (you can feed it a password filename), although it doesn't hurt to have both.

Could you please commit scenario image(s) so it's clearer what the scenario_image generator does. 

@thomashaw, how does this leak_to_file module compare to the lead_data feature you added?

Thanks.

**Comment by cliffe** [comment]
The files in SecGen/lib/resources/passwordlists should probably move to SecGen/lib/resources/wordlists for consistency (and move any licencing comments into a shared README in the resources directory.

**Comment by profzeller** [comment]
Intention behind scenario image was instead of using random_image, this allowed you to choose a particular image you may have created for the scenario. For example, using the paramatised_website, we uploaded file which was then used scenario_image to convert to base64. From there strings and flags were embedded. This way the end result fit the narrative of the scenario.

**Comment by profzeller** [comment]
leak_to_file was created to take any base64 encoded file and let you out anywhere on the system, owned by a user or root by default. Functionality was ripped from parameterised_accout.

I origonally had the password lists in word lists, so I don't see a problem, except I needed to verify any of the random generators doesn't just randomly select a file from word list directory, which would give unintended result.

**Comment by Th3Prim3** [comment]
Sorry just getting back to these:

custom_list_password, I see you created random_word_password during the same time I built this code. I am good either way, just let me know what you thing.

scenario_image_generator, let me know if I need to update the metadata and if so, what you might like to see.

**Comment by cliffe** [comment]
Sorry for the review delay. I'm going to accept this, but we can also change the password generators to match the approach taken elsewhere in SecGen. Thanks again!

**Pull request merged**
