### PR TITLE
Samba secure service module

### PR DESCRIPTION
**Pull request by Jjk422**
Samba secure service module and example scenario file. Requires update module to function. Should be fully working and should be able to connect to the samba server from the host machine.

### CODE REVIEW

**Comment by thomashaw** [comment]
Gonna take a look now, cheers mate.

**Comment by Jjk422** [comment]
The update module should already be in the Cliffe/SecGen master code. I'm going to include exec {apt-get update} to all existing services to make sure they can run as standalone modules without erroring. The exec code can be removed later when code checking for dependencies is written by someone later.

**Comment by thomashaw** [comment]
testing now, cheers:)

**Comment by Jjk422** [comment]
This should be fully working and ready to be merged.

**Pull request merged**
