### PR TITLE
CTFd Export/Import Fix

### PR DESCRIPTION
**Pull request by Th3Prim3**
CTFd import was broken during CTFd rewrite. This makes SecGen compatible with CTFd v2.0.2+. This does require a Python3 script to be execute to generate password. Ruby's bcrypt gem does not support the 2b variant. I searched high and low but could not find a replacement in Ruby. This script uses the same library as CTFd which ensures compatibility.

### CODE REVIEW

**Comment by cliffe** [comment]
Great. 

It is disappointing to have to include python 3 as a dependency just to get bcrypt 2b passwords, but I also couldn't find any existing ruby solution. Could you please also update the README including python3 python3-passlib (and whatever backend is needed) in the (Ubuntu) install instructions; preferably using apt-get rather than pip to keep things consistent.

**Comment by Th3Prim3** [comment]
I don't believe there is any additional Python requirements.

**Comment by cliffe** [comment]
I've had a chance to think about this some more: how about we hard code the password string? 
`"password"=>password_hash_string("adminpassword"),`
becomes
`"password"=>"HARD CODED HASH",`

There is some other dependency because when I try to run it I get an error about missing a back end.

**Comment by Th3Prim3** [comment]
That was a thought I had, didn't want to take away functionality you had. However, is a more elegant solution. What we can do is plug in the hash with a comment above what it is and a comment to point to Python script. In that script, documentation of what is required to run it, should the user want to generate something else. Keeps Python out of project. However, somewhere when I was building scenarios I ran into this exact issue but couldn't find my notes where. I was to say it was a password on Linux or a database.

I have a bunch of code with lots of vulnerabilities, generators, etc. However, since then you both have made a ton of commits so I am trying to pull out anything universal that you didn't already fix. Been out of the git game for a few years, remembering why I used to keep commits fairly small. Will try to weed through them and create other pull requests.

I will be sending an email to you soon on a planned workshop I have this summer using SecGen. Like to gather more information from you.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by cliffe** [comment]
Great. Yes, please do.

I also look forward to some more pull requests with more vulnerabilities and generators!

**Comment by Th3Prim3** [comment]
Updated per conversation.

**Comment by Th3Prim3** [comment]
Standby, I realized I was not checking against your current master. Let me verify everything is ok. You added some other required packages/gems.

**Comment by Th3Prim3** [comment]
Tested and verified.

**Comment by redwiz666** [comment]
@Th3Prim3 
I did a pull of your fix and it allows the file to be imported but it doen't set the flags. I took a closer look at the flag.json file and noticed that the "challenge_id" is only being referenced as "cha". Looking through lib/output/ctfd_generator.rb I found the issue on line 69. The line is currently "cha_id"=>challenge_id, but it should be "challenge_id"=>challenge_id,
I built a few projects and imported them into ctfd and verified it work.

**Comment by Th3Prim3** [comment]
These have been fixed. Thanks for finding those.

**Pull request merged**
