### PR TITLE
change repos to use debian archive

### PR DESCRIPTION
**Pull request by JD2344**
Recent changes to debian repositories, mean stretch is being archived from this point on. These updates reflect those changes.

### CODE REVIEW

**Comment by cliffe** [comment]
This change needs to happen in the Stretch base -- I'm not sure that adding stretch repos to buster, is the safest way to install openjdk. Are their many dependencies being pulled in?

**Comment by JD2344** [comment]
Looking at this issue, seems we can either deal with it by either pulling the original deb, which will increase the size of the project, or link to the debian "unstable" repos known as "sid". 

https://wiki.debian.org/DebianUnstable

I'd say linking to sid is the better route. I have tested with newer openjdk versions, with no success. It also seems the unstable repo still has openjdk-8 available:

https://tracker.debian.org/pkg/openjdk-8

**Comment by cliffe** [comment]
My concern would be that adding another repo could result in unexpected behaviour when subsequent installs happen -- could end up with different versions of software, such as say, Firefox, from Sid. Maybe script it to add the repo, do the install, then remove the repo?

**Comment by cliffe** [comment]
Snapshots is a good idea for future issues that are similar. Ok, I'll merge this for now, and see how this holds up.

**Pull request merged**
