### PR TITLE
Module dependencies

### PR DESCRIPTION
**Pull request by cliffe**
Any module can include in secgen_metadata.xml \<requires> tags to require other modules that satisfy a set of conditions are also in the scenario. When selecting a module, each dependency is resolved by checking if a module already satisfies the condition, in which case nothing happens, or a module that satisfies all the conditions is randomly selected and added to the scenario. This is recursive so a module can require modules that require modules. 

When conflicts occur (say for example, a previously selected module conflicts with all the valid options for resolving a dependency) the scenario is regenerated. This bruteforce approach is fairly effective, but \<conflict> tags should be avoided wherever possible because they add complexity and reduce randomisation possibilities.

A module can have multiple \<requires>, each of which will ensure a single module fulfills all of the conditions, which are regexp matches against attributes.

For example, for a module that needs to have a repo refresh (apt-get update) first:
````  
  <requires>
    <type>update</type>
  </requires>
````
Or for a module that requires apache be installed by another module (rather than the module itself installing apache, alternatively):
````
<requires>
    <type>httpd</type>
    <software_name>apache</software_name>
  </requires>
````

In this (silly) example, writable_shadow requires apache which requires update:
recursive_dependencies

In another silly example, here apache requires ftp, but all ftp modules conflict with writable_shadow: 
recursive_dependency_resolution

Still TODO: treat base modules separately

### CODE REVIEW

**Comment by cliffe** [comment]
This is ready for testing and merging. The base box platform matching will be added at a later stage.

**Comment by Jjk422** [comment]
Tested before and was working as desired.
Quickly tested again and still seems fine:
I however do not like the error
`Failed to resolve scenario. No conflicts, but failed to resolve scenario -- this is a sign there is something wrong in the config (scenario / modules). Please review the scenario -- something is wrong.`
due to the fact that this points more towards the scenario rather then the module that is actually wrong. In other words more detailed error messages, ones that are show the file containing the error. However, generic error messages are not as much of a big deal with smaller scenarios, just larger ones/chains of requires modules.

But other than that everything seems to be working with the pull request so should be ready to be merged.

**Comment by thomashaw** [comment]
Also tested and it appears to be working great :)

Would be happy to merge it with the testing comments you left (thanks!) in default_scenario.xml and secgen_metadata.xml removed.

Cheers!

**Comment by cliffe** [comment]
Thanks @thomashaw and @Jjk422. 

@Jjk422, the proceeding output before the error includes all the details for figuring out what went wrong, although perhaps that error message should point that out.

**Pull request merged**
