### PR TITLE
Access control vulnerability, allows less to run as root for any user.

### PR DESCRIPTION
**Pull request by Jjk422**
Access_control_misconfigurations_uid_less_root.xml can be used to test.
Should be able to read any file from any user account with less.

### CODE REVIEW

**Comment by thomashaw** [comment]
testing now, thanks :)

**Comment by thomashaw** [comment]
Hey,

Works great, couple of suggestions before merging.

required: 
/access_control_misconfigurations/uid_less_root/manifests/change_uid_permissions.pp:4: Remove comments please.
/access_control_misconfigurations/uid_less_root/manifests/change_uid_permissions.pp:10-15: remove comments please.

optional / suggested:
/access_control_misconfigurations/uid_less_root/manifests/change_uid_permissions.pp:1: If you like you can remove the parameter for user from here (and the manifest) and just specify 'root' directly. 
/access_control_misconfigurations/uid_less_root/manifests/change_uid_permissions.pp:2: You can remove the 'String' from before the block parameter definitions.
/access_control_misconfigurations/uid_less_root/manifests/change_uid_permissions.pp:3-8(post comment removal): I've made the above changes and indented this block with 2 spaces for ease of reading, screenshot below:

change_uid_permissions_pp

Cheers!

**Comment by Jjk422** [comment]
I'll do the changes now then I'll update them to this branch.

**Comment by Jjk422** [comment]
All changes should be done other then the removing the user parameter.
The reason why I wanted to keep the user parameter is to ensure that any access control modules can use a similar/same base code, ensuring that the code is correct and easy to identify for all of the file altering modules.
I would like to know if you think it is a good idea, or does it only sound like a good idea for me.
To be honest most of the code base for the access control modules and file/software misconfiguration can be fed through one module, however it probably is a good idea to ensure all the modules are separated to ensure randomization and selection features of SecGen work correctly.

**Comment by thomashaw** [comment]
I see where you're coming from and it does make sense if you're going to re-use this class for changing file permissions in this way. 

We should aim to minimise code duplication wherever possible in order to improve maintainability (so we don't have to hunt and make the same change in multiple places). 

I'd be happy to merge it as it is. You can decide how you want to structure the code with your next access control module.

Cheers!

**Comment by Jjk422** [comment]
To be honest most of the code for the modules could go into an encoding module, making sure no duplication occurs. I'll look into that in a bit to see how I can do it to link all the access control modules together.

**Comment by Jjk422** [comment]
I was going to change this branch to allow for most of the code to be reusable, but its fine I'll do it in the next pr, it'll give me something to test the theory against.

**Pull request merged**
