### PR TITLE
Added a new CTF challenge 'Decoder'

### PR DESCRIPTION
**Pull request by Josh1438**
Adding a new CTF challenge Decoder under scenarios/ctf

### CODE REVIEW

**Comment by cliffe** [comment]
Thanks, Josh! I'm spinning up some VMs to have a look.

Please add some metadata to the xml, to give the scenario a title (to display to users) and any instructions.

For example, this is from the narrative CTF scenario:
```
  <name>Basic Narrative</name>
  <author>Thomas Shaw</author>
  <description>Single system narrative-based CTF challenge.
  </description>

  <type>ctf</type>
  <type>attack-ctf</type>
  <type>web-hints</type>
  <difficulty>intermediate</difficulty>

```

**Comment by cliffe** [comment]
Hi Josh,

First of all, thanks for submitting the scenario, it looks like a solid foundation for a fun CTF. The flag fragments approach looks like it will work well.

There's a bunch of things about the scenario that aren't working quite as you intended. Happy to talk through this in person, but here are a few points. I am posting this to GitHub because these are all really easy mistakes to make, and likely others may benefit from seeing this feedback.

On line 126 you have a bunch of encoders feeding things into a datastore named trials. You have an encoder that encodes a message and a flag fragment (as two separate strings_to_encode), followed by another encoder combining things for the second trial and so on. Then you (not that unreasonably) assume that you can read the first element of trials to get the first set of things you encoded (the message and flag fragment). But actually the encoder outputs two encoded strings, and all the inputs into the trials datastore collapse into a one dimensional array, so when you access the first element from trials you actually only get the first "here you go" text, which you place in trial1.txt and the first flag fragment actually ends up in trial2.txt

You could fix that by using separate datastores for each trial, which can be fed into a single file, or you could create an encoder to combine the strings into a single string output to get the behaviour you expected. (I don't think we have a concat secgen encoder module but it would only be a few lines of code -- just do a join on the strings_to_encode and output that single string.)

There is also a known minor issue where input values are received before datastore accesses, regardless of the order sent. It's an issue that I'll fix at some point, but for now just work around it by not assuming you can input value1, then datastore2, then value3, then datastore4, as it will actually end up displayed as value1, value3, datastore2, datastore4.

Also you can't really reverse an input that gets hashed, unless the input is guessable/crackable, so you probably want to change the first trial to use a reversible_string_encoder (or have a hashed input that they crack be the password to access something else).

Finally... I love the Rick and Morty avatar!

Cheers,

Cliffe.

**Comment by Josh1438** [comment]
Hi Cliffe,

Sounds good I’ll have a look over them a little later on, just finishing a few bits on my project.

I have a meeting booked in with you tomorrow at 11:40, just have a few questions about my project so I can have a chat then about the CTF. 

Thank you,

Josh

**Comment by cliffe** [comment]
Hi Josh. You've messed up the pull request by pulling from your master, rather than a separate branch for this feature (CTF scenario). Next time create a new branch with your changes, before you make your pull request.

**Pull request closed without merging**
