### PR TITLE
Iptables firewall configure

### PR DESCRIPTION
**Pull request by Jjk422**
Fully completed firewall module and scenario file. Update code built into module, to be removed if/when dependency code is added.

### CODE REVIEW

**Comment by cliffe** [comment]
Just a couple of quick comments about secgen_metadata.xml (sorry, I realise this is not well documented):

author should include yourself, in addition to authors of any contained puppet module off the forge

references should include URLs for the source of any puppet modules that have been copied into the folder

software_name should be the (common) name of packages installed, for example, if this actually installs "iptables", otherwise just leave off if its just config changes

Thanks.

**Comment by Jjk422** [comment]
All the changes mentioned should have been amended for the secgen_metadata.xml file for this module.

**Comment by thomashaw** [comment]
testing this one now, cheers :)

**Comment by thomashaw** [comment]
Correctly applies the default firewall rules found in firewall.pp to the box. This module will enable the creation of new vulnerable iptables configurations.

firewall rules applies

**Pull request merged**
