### PR TITLE
Changed Object variables to Object attributes hashes

### PR DESCRIPTION
**Pull request by Jjk422**
Changed Object variables to Object attributes hashes

### CODE REVIEW

**Comment by thomashaw** [comment]
Hey mate, couple of minor changes. Cheers + for creating one commit really appreciated.  Couple of minor things and it's good to go.

[CR PR #24.txt](https://github.com/cliffe/SecGen/files/275991/CR.PR.24.txt)

Easiest way to revert a full file's changes in RubyMine is to find the commit in the log, select the file you want to revert on the right hand side and click the purple 'revert' arrow. this will put the reverted changes in your local changes change list

Cheers, 
Tom

**Comment by Jjk422** [comment]
All changes should have been implemented hopefully. May have not merged properly but looks alright, although vulnerability_helper.rb was not reverted to old code (new code should still work though).

**Comment by thomashaw** [comment]
Just tested it again and there's one minor thing to change and i'll merge it.

In bases.xml you've removed the duplicate debian-puppet-32 line, but you've also reverted the change on line 7 which you previously fixed. 

The attribute 'vagrantbase' is "debian-puppet-64" where it should be "debian-puppet-32".

As your scenario.xml has a base box of "debian-puppet-32" SecGen is searching for that base box, finding nothing, then choosing a random box. 

Re: the vulnerability_helper.rb reverts, no worries this time but the reason I suggested it was just to reduce clutter in the git history. There's no real need to change code that is functionally equivalent as it clutters up the change log making it harder to review and conduct merges - it's a bit nit picky but a good habit to get into! 

Cheers,
Tom

**Comment by Jjk422** [comment]
Ok, I'll change the bases.xml, was wondering why it was picking random boxes but couldn't find anything in code, missed the vagrantbase part in the xml. And I'd prefer to learn and use best practice now when I'm still learning how to use everything.

**Comment by thomashaw** [comment]
good work, cheers and well done :+1:

**Comment by Jjk422** [comment]
Thanks, hopefully I haven't broken anything.

**Pull request merged**
