### PR TITLE
Vulnerability: samba anonymously writable share + symlink traversal

### PR DESCRIPTION
**Pull request by thomashaw**
I have two samba misconfiguration vulnerability modules here. 

The first adds a public anonymously accessible share with read / write privileges, the second makes further modifications enabling symlink traversal out of the share.

The samba_public_writable_share module allows the creation of the symlink but gives an access denied error when trying to use it:
public-writable-cd-rootfs-access-denied

The samba_symlink_traversal module modifies the configuration to remove some of the built in security of samba. Versions of samba before 3.4.5 had 'unix extensions = yes' and 'wide links = yes' set by default. The latest version requires you to add an additional line in the [global] section of the configuration to 'allow insecure wide links = yes' if you want the same insecure behaviour.

cd-rootfs-ls

Grabbing the /etc/passwd file:
symlink_traversal_get_etc_passwd

Let me know what you think!

Cheers,
Tom

### CODE REVIEW

**Comment by Jjk422** [comment]
I think I had a branch for the samba 3.4.5 symlink_traversal vulnerability, :D.
I'll test these in a bit and see if I can get them to work, then hopefully we can merge them.

**Comment by Jjk422** [comment]
I have managed to get the vulnerability module samba_symlink_traversal to work.
I was unable to find if there was any workable output from the vulnerability module samba_public_writable_share and therefore I presume it is just required for the vulnerability module samba_symlink_traversal to work, if this is the case I don't see any point in keeping the samba_public_writable_share.xml scenario file.
I may be missing something that is obvious, I am curious to know if I am or not.
Another point is that you require the samba service module, however I believe that takes the most up to date version of samba at the moment (it can be passed a version argument), therefore if the samba defaults are changed (although it should be alright after samba 3.4.5) it may break the module.
Could be avoided with a facter version argument to the samba service module, just food for thought.

**Comment by thomashaw** [comment]
The samba_public_writable_share.xml scenario does just that, creates a samba share which is anonymously read/writable. There's no associated metasploit module with it but it's a poor configuration so I left it in, can remove if preferred.

Yeah good thinking, unfortunately I've already tried that with no luck :P Tried passing the version argument and had an error as there's no samba <=3.4.5 on the ubuntu apt repositories. Downloaded the .tar.gz and built it from source manually with a lot of trouble + ended up deciding it was easier to just implement the misconfigurations (wide links = yes, follow symlinks = yes, allow insecure wide links = yes in the smb.conf), which existed in 3.4.5  but were removed from the default configuration.

I do still think it'd be a good idea to create a samba <=3.4.5 module as scanning this box spits back a version number >3.4.5 but it ended up taking significantly longer to figure out than i was happy to spend on it so I moved on.

**Comment by Jjk422** [comment]
Ye, good points, we could do a separate samba service module that builds from source from the samba repos (although that would take considerably longer) and could introduce tons of errors, I think at the moment its fine, we'll edit it later if it becomes a problem.
[samba repos: https://download.samba.org/pub/samba/ => 3.0.37 - 4.4.5 || https://download.samba.org/pub/samba/old-versions/ => 1.5.14 - 2.2.12].

p.s. Might check to see if it was there is a problem with the samba service versioning (just to make sure).

p.p.s I don't mind the branch being there, it makes it look like SecGen has more modules and therefore is far more useful

**Comment by thomashaw** [comment]
by all means if you can find a better way of doing it go ahead and let me know :)

**Pull request merged**
