### PR TITLE
Sprint 3 object attributes as hash not variables

### PR DESCRIPTION
**Pull request by Jjk422**
Changed all object variables to a hash for easier access and checking abilities. Tell me if I have any mistakes or need to change anything.

### CODE REVIEW

**Comment by Jjk422** [comment]
This update has conflicts now due to recent merge. Will be resolved later.

**Comment by thomashaw** [comment]
Taking a look at this now for you mate, will give you feedback :)

**Comment by cliffe** [comment]
@thomashaw it's probably worth waiting for @Jjk422 to resolve merge conflicts before reviewing.

**Comment by Jjk422** [comment]
Hopefully should be fully done now.
Last commit contains what I mostly changed:
Scenarios.xml only contains networks.
	Condensed all object variables into an object attributes hash.
	Changed all local variables related to objects into attributes[:variable] values.
	Should be fully working.
	Also changed version number to 0.0.1.1 as minor changes done.

	If I need to improve my code or if i've broken something, tell me and I'll fix it.
	Hopefully this should work on everyone's computers.

**Comment by Jjk422** [comment]
Oh and before I forget the variable ROOT_DIR should in my opinion be ../../ not ../../../SecGen.

**Comment by cliffe** [comment]
> ROOT_DIR should in my opinion be ../../
Sounds good. Code welcome :-)

**Comment by Jjk422** [comment]
The newest commit seems to break vulnerabilities as it doesn't discount nulls, I think this is due to the ||= operator instead of the if not nil so therefore placing empty strings in the vagrant file, I'm not sure though. Only realized this after pushing the commit.

**Comment by thomashaw** [comment]
image

OK cool, looks like I misunderstood what ||= did, it will assign the operand if the variable is nil. I thought it might work with empty strings also but I guess not.

**Pull request closed without merging**
