### PR TITLE
REMA updates for 2021-22

### PR DESCRIPTION
**Pull request by tvergilio**
Updated lectures to point to new videos and reorganised the labs to match this year's delivery.

### CODE REVIEW

**Comment by cliffe** [comment]
Not sure if you've done so, but the README file should be autogenerated by running `SecGen/lib/CyBOK/generate_scenario_index.rb`

**Comment by tvergilio** [comment]
Ah, thanks for the tip. I knew it was generated, it just didn't occur to me to look for the generating code within SecGen. I'll do it like this next time.

**Comment by cliffe** [comment]
The videos are specified in the scenarios themselves (and that's what's used in Hacktivity to list videos per lab), the readme file is just for reference

**Comment by tvergilio** [comment]
Thanks. I have updated them in the scenarios, so it should be good to go.

**Pull request merged**
