### PR TITLE
Some minor changes

### PR DESCRIPTION
**Pull request by meehien**
Last commit is a bit ambiguous. Sorry for that...

### CODE REVIEW

**Comment by thomashaw** [comment]
Hi Mihai,

I tested the pull request and ran into an issue with the Debian 8.2 basebox.  I'm running secgen on my machine (running Fedora 24) and the VM does not initialise the networking capabilities correctly during start-up and has an inconvenient 1 minute time-out. 
network_interface_problem1

I logged onto the box and checked 'ifconfig eth0', the interface had not been assigned an IP (2).
network_interface_problem2

I worked around this manually by running dhclient and restarted the networking service. This allowed the vagrant provisioner to communicate with the VM via ssh. 
network_interface_problem3

I couldn't find anyone else describing the same problem online so I can't tell if this is just on my end. I updated Vagrant and VirtualBox to the latest versions and re-added the base box, but had the same results.

The rest of the changes are working fine, but I'm hesitant to merge the new base into master until this gets figured out.  I don't like the idea of having to wait a minute, log onto the box and fix the networking before provisioning each time.  We're on a tight time-schedule until the first CTF event we're hosting with SecGen (March 24th!) so can't afford to dig further into the cause of this right now. 

To narrow it down I'd like someone else to test the new basebox if possible, and see if they have the same issue.  @cliffe  @Jjk422 (or Gajendran, if anyone's in touch with him).

If anyone has any ideas for potential solutions please let me know.

Cheers,
Tom

**Comment by Jjk422** [comment]
I seem to have experienced the same error from the Debian 8.2 basebox, whereby the IP address is never assigned to the system and vagrant times out waiting for the machine to become available.
I am running on an Ubuntu 16.04 host system so I don't think it is a host configuration error.

**Comment by meehien** [comment]
Try enabling some of the HW virtualization. That was the behavior I was experiencing until I enabled "hwvirtex". You can do it with --hwvirtex if you have the version with the new command line options enabled.

**Comment by cliffe** [comment]
Just meeting with @thomashaw now. @meehien, could you please remove the new base box from this pull request then we can accept the rest of the pull request. 

New basebox _should_ be fine, but would require testing quite a few modules to increase confidence everything is working as expected, and all the vulnerabilities are still vulnerable -- also probably makes sense to make --hwvirtex the default behavior in that case.

**Comment by cliffe** [comment]
Hi @meehien, if you use separate branches to make your changes, we can pull in the things we have reviewed, while you are working on and committing other things. Since your pull request is from your master, I am not sure if you are indicating that the ssh leaked keys module is also ready for testing to be merged. If you put that in a separate branch we can review and merge more easily/quickly.

**Comment by cliffe** [comment]
(Looks like you are getting on really well though!)

**Comment by cliffe** [comment]
@thomashaw could you please review this pull request again, once @meehien lets us know it is tested and ready for merging. Thanks!

**Comment by meehien** [comment]
yes. ssh_leaked_keys has worked on my tests.

**Comment by thomashaw** [comment]
Tested and it works fine, thanks a lot.  

1 suggestion: In future could you please create an example scenario file for each vulnerability to be tested containing only that vulnerability (e.g. below). I've created one for you that I used whilst testing which I'll push up after merging the PR.
image

Testing steps:
* Created another account on the box.
* Copied and unpacked the /home/username/.ssh/.ssh.tar.gz directory
* Copied the id_rsa from the tar.gz to the new user's ~/.ssh/id_rsa 
* ssh username@ip
* cat flag.txt

**Pull request merged**
